### ISSUE TITLE
ZHA alarms incompatible with keyfobs because of requirement for pin code

### ISSUE THREAD

**Issue by M0ORY** [zigpy/zha#195]
I recently picked up a couple of Zigbee alarm keyfobs from Aliexpress https://www.aliexpress.com/item/4001062612446.html They work just fine for arming, home arming or panic button operation but I'm having difficulty getting them to disarm the alarm because ZHA requires a master pin / code for alarms which has to be sent with the disarm signal. This behaviour is fine for keypad style systems but doesn't work for fobs as there is no way to enter a code. A keyfob it's self can be considered secure since it's personal to each user and not screwed to a wall at a given entry point and for single person households keyfobs are much more appropriate than key pads which also tend to be much more expensive and are fairly hard to come by.

**Comment by puddly** [comment]
Are these actual alarm devices or is this a generic four button remote control?

Tuya devices often aren't proper Zigbee and implement a protocol on top. Please attach the diagnostics JSON for your device, as this will contain enough info to identify what exact device this is. Also, please enable ZHA debug logging and run through the operations of the device, as this will show what the device sends over the network.

**Comment by M0ORY** [comment]
Yes it create an alarm control panel device when paired along with an IAS zone sensor but I'm not sure what that is or how I'm supposed to use it at present. I was actually hoping it would be a generic 4 button remote as that would have been simple to set up. From what I've seen in the logs they seems to send multiple commands for each button push but that doesn't seem to be an issue aside from hitting the max failed disarm tries as little sooner than you'd expect which isn't a problem if the disarm works without a code anyway. I think I've got the disarm tries set to 6 at the moment and it takes a couple of pushes of the disarm button and the alarm activates because it doesn't get a code.

Thanks for taking a look for me. I think I've attached everything you asked for here.

[zha-b456122ea7a3436191d4cfd498f2ea8e-_TYZB01_qm6djpta TS0215-50171b10baefb4e48cb8172122ad3470(1).json](https://github.com/user-attachments/files/16880909/zha-b456122ea7a3436191d4cfd498f2ea8e-_TYZB01_qm6djpta.TS0215-50171b10baefb4e48cb8172122ad3470.1.json)

[home-assistant_zha_2024-09-04T21-13-16.290Z.log](https://github.com/user-attachments/files/16880944/home-assistant_zha_2024-09-04T21-13-16.290Z.log)

**Comment by Hedda** [comment]
FYI, I think that this is indirectly related to this previous issue dicussion that are about zigpy/zha fully supporting Zigbee IAS:

* https://github.com/zigpy/zigpy/issues/419

> Are these actual alarm devices or is this a generic four button remote control?

Anyway, I also tried researching that specific model (Zigbee ID: RC_V14 | RC-EM | RC-N | RC-EF-3.0) from Tuya without much luck:

* https://www.zigbee2mqtt.io/devices/HS1RC-EM.html

* https://zigbee.blakadder.com/Heiman_HS1RC.html

Also tried researching this other similar Tuya model (Zigbee ID: TS0215A | _TZ3000_p6ju8myv | _TZ3000_0zrccfgx) which are also readily available to order from both China and resellers in the EU:

* https://www.zigbee2mqtt.io/devices/TS0215A_remote.html

* https://zigbee.blakadder.com/Woox_R7054.html

At least according to Zigbee2MQTT's device documentation both do have possible values for: `disarm`, `arm_partial_zones` or `arm_day_zones`, `arm_night_zones`, plus `arm_all_zones`, and `emergency`, (as well as values for `battery` and `linkquality`).

Will follow this as curious too what the answer to that question is myself because looking to find key fob to use with Alarmo:

* https://github.com/nielsfaber/alarmo

PS: I don't want it for myself, but my father had similar-looking key fobs for his old security alarm system so thinking of replacing that with a Zigbee-based solution (which can hopefully be using Alarmo with all devices connected via ZHA in Home Assistant).

**Comment by M0ORY** [comment]
In case it's of any use here are the events I've captured for arming and disarming and I see the code is always an empty string but ZHA enforces a master code be set in the alarm panel config. Maybe there's some way to send a zigbee command to it to give it a code to send with future button pushes but if there is I'm not sure how to do that and I can't find any information about things like that. 

```
event_type: zha_event
data:
  device_ieee: 2c:11:65:ff:fe:f6:0e:2f
  unique_id: 2c:11:65:ff:fe:f6:0e:2f:1:0x0501
  device_id: 50171b10baefb4e48cb8172122ad3470
  endpoint_id: 1
  cluster_id: 1281
  command: arm
  args:
    arm_mode: 1
    arm_mode_description: Arm_Day_Home_Only
    code: ""
    zone_id: 255
  params: {}
origin: LOCAL
time_fired: "2024-09-06T14:40:31.819945+00:00"
context:
  id: 01J73WF5JBNSSVZ1J8CED61NF5
  parent_id: null
  user_id: null

event_type: zha_event
data:
  device_ieee: 2c:11:65:ff:fe:f6:0e:2f
  unique_id: 2c:11:65:ff:fe:f6:0e:2f:1:0x0501
  device_id: 50171b10baefb4e48cb8172122ad3470
  endpoint_id: 1
  cluster_id: 1281
  command: arm
  args:
    arm_mode: 3
    arm_mode_description: Arm_All_Zones
    code: ""
    zone_id: 255
  params: {}
origin: LOCAL
time_fired: "2024-09-06T14:42:06.986829+00:00"
context:
  id: 01J73WJ2GAXB9ACF692N17ZWDQ
  parent_id: null
  user_id: null

event_type: zha_event
data:
  device_ieee: 2c:11:65:ff:fe:f6:0e:2f
  unique_id: 2c:11:65:ff:fe:f6:0e:2f:1:0x0501
  device_id: 50171b10baefb4e48cb8172122ad3470
  endpoint_id: 1
  cluster_id: 1281
  command: arm
  args:
    arm_mode: 0
    arm_mode_description: Disarm
    code: ""
    zone_id: 255
  params: {}
origin: LOCAL
time_fired: "2024-09-06T14:44:32.641678+00:00"
context:
  id: 01J73WPGR1H759CN2VADEV21HR
  parent_id: null
  user_id: null
```
