### ISSUE TITLE
GLEDOPTO GL-SD-001P incorrectly added as a RBGWW device

### ISSUE THREAD

**Issue by dephcon** [zigpy/zha#459]
Hello,

I've recently added a couple GLEDOPTO GL-SD-001P dimmer relays and they're not detected properly by ZHA.  These are just triac dimmers, no RGBWhatever control.

I've manually addressed this in configuration.yaml, but hoping this could be fixing upstream:

```
homeassistant:
  customize:
    light.deck_pergola_lights:
      min_color_temp_kelvin: null
      max_color_temp_kelvin: null
      supported_color_modes:
        - brightness
      color_mode: null
      color_temp_kelvin: null
      color_temp: null
      hs_color: null
      rgb_color: null
      xy_color: null
```

Thank you!

**edit** just realized this is the wrong repo for this
